name: ci

on:
  pull_request:
  merge_group:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  build-test:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install deps
        run: npm install

      - name: Run tests
        run: npm test

      - name: Report status
        run: echo "ci completed"
