name: doc-validate
on:
  pull_request:
  merge_group:
  push:
    branches: [ main ]
jobs:
  doc-validate-logic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Documentation valid."
  doc-validate:
    needs: [doc-validate-logic]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Always-Report
        run: |
          if [[ "${{ needs.doc-validate-logic.result }}" == "success" || "${{ needs.doc-validate-logic.result }}" == "skipped" ]]; then exit 0; else exit 1; fi
